### ISSUE TITLE
SQL upgrade

### ISSUE THREAD

**Issue by ritagin** [wiso-forschungslabor/hroot-documentation#4]
I want to upgrade SQL version from 5.1 to 5.7
Of course, I make a backup. Should there be any problem?
Thank you.

**Comment by ib-fhgr** [comment]
I have used the version 5.7 with out any problems - so I believe an update should not cause any issues.

**Comment by n0c1urne** [comment]
I have used the version 5.7 without any problems - so I believe an update should not cause any issues.
