### ISSUE TITLE
password reset issue

### ISSUE THREAD

**Issue by ritagin** [wiso-forschungslabor/hroot-documentation#5]
Hello, 
System does not allow to reset password - fill out a form to reset a password, and then receive an empty email without a link to reset a password.
Thank you for your help,
Rita Ginzburg

**Comment by n0c1urne** [comment]
Hello,

please check if you have added an email template for the password reset email - you can find this in "Site settings / Email templates" in the section "Email for setting a new password".

You can author the email text yourself, but be sure to include a marker to include the password reset link (#link), like so:

```
Hello,

please use this link to change your password:

#link

(info on how to contact you)
```

If this doesn't resolve your issue, please report back here.
